services:
  - type: web
    name: springboot-sms
    runtime: java
    plan: free
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -Dserver.port=$PORT -jar target/*.jar
    envVars:
      - key: JAVA_VERSION
        value: 21
      - key: MAVEN_VERSION
        value: 3.9.0
